# Generated by Django 5.0 on 2024-07-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('statut', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=0)),
                ('adresse', models.CharField(max_length=355)),
                ('ville', models.CharField(max_length=150)),
                ('pays', models.CharField(max_length=150)),
                ('coordonnees_tel', models.CharField(max_length=20)),
                ('nombre_de_chambres', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotel_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3000)),
                ('type_de_plat', models.CharField(choices=[('entrée', 'Entrée'), ('plat principal', 'Plat Principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menus_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('statut', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=0)),
                ('adresse', models.CharField(max_length=355)),
                ('ville', models.CharField(max_length=150)),
                ('pays', models.CharField(max_length=150)),
                ('coordonnees_tel', models.CharField(max_length=20)),
                ('nombre_de_tables', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='restaurant_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('type_de_chambre', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('suite', 'Suite')], max_length=20)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarif_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vue_sur_mer', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('emplacement', models.IntegerField(choices=[(1, '1er étage'), (2, '2ème étage'), (3, '3ème étage'), (4, '4ème étage'), (5, '5ème étage')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chambre_photos/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='frontend.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='frontend.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambre_images/')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='frontend.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='frontend.menu')),
            ],
        ),
        migrations.CreateModel(
            name='PrestationHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activites', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('reception_evenements', models.JSONField(blank=True, default=list)),
                ('langues_personnel', models.JSONField(blank=True, default=list)),
                ('methodes_paiement', models.JSONField(blank=True, default=list)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='frontend.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='frontend.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='frontend.restaurant'),
        ),
    ]
