# Generated by Django 5.0 on 2024-07-09 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(blank=True, default=list)),
                ('langues_personnel', models.JSONField(blank=True, default=list)),
                ('methodes_paiement', models.JSONField(blank=True, default=list)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='frontend.restaurant')),
            ],
        ),
    ]
