# Generated by Django 5.0 on 2024-07-18 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_restaurant_is_validated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('moyen_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_confirmation', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_confirmer', models.BooleanField(default=False)),
                ('validation', models.CharField(default='En cours de validation', max_length=50)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.chambre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
