# Generated by Django 5.0 on 2024-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_reservationchambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='vue_sur_mer',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], default=('non', 'Non'), max_length=3, null=True),
        ),
    ]
