# Generated by Django 5.0 on 2024-07-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_chambre_vue_sur_mer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationchambre',
            old_name='date_debut',
            new_name='date_arrivee',
        ),
        migrations.RemoveField(
            model_name='reservationchambre',
            name='date_fin',
        ),
    ]
