# Generated by Django 5.0 on 2024-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_rename_date_debut_reservationchambre_date_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='tarif_reservation_par_jour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
