# Generated by Django 5.0 on 2024-07-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_chambre_tarif_reservation_par_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='prix_reservation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
