# Generated by Django 5.0 on 2024-07-30 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_restaurant_prix_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('moyen_paiement', models.CharField(max_length=50)),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_confirmation', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_confirmer', models.BooleanField(default=False)),
                ('validation', models.CharField(default='En cours de validation', max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
