# Generated by Django 5.0 on 2024-08-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_reservationchambre_statut_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRestaurantPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.reservationrestaurant')),
            ],
        ),
    ]
