# Generated by Django 5.0 on 2024-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_reservationrestaurantpaiement_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrestaurantpaiement',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
