# Generated by Django 5.0 on 2024-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_reservationrestaurantpaiement_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrestaurantpaiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
