# Generated by Django 5.0 on 2024-08-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_reservationrestaurantpaiement_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationrestaurantpaiement',
            old_name='numero_telephone',
            new_name='numero_telephone_destinataire',
        ),
        migrations.AddField(
            model_name='reservationrestaurantpaiement',
            name='votre_numero_telephone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReservationHotelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votre_numero_telephone', models.CharField(max_length=20)),
                ('numero_telephone_destinataire', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.reservationchambre')),
            ],
        ),
    ]
