# Generated by Django 5.0 on 2024-08-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_rename_numero_telephone_reservationrestaurantpaiement_numero_telephone_destinataire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationchambre',
            name='moyen_paiement',
        ),
        migrations.RemoveField(
            model_name='reservationrestaurant',
            name='moyen_paiement',
        ),
    ]
